version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.0
jobs:
  build:
    working_directory: ~/opendjbooth
    docker:
      - image: cimg/ruby:3.1.2-browsers
        environment:
          RAILS_ENV: test
          # PGHOST: localhost
          # PGUSER: postgres
          # PGPASSWORD: postgres
          # HOST: ''
      # - image: postgres:9.5
      #   environment:
      #     POSTGRES_USER: postgres
      #     POSTGRES_DB: opendjbooth_test
      #     POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver

      # Restore Cached Dependencies
      - restore_cache:
          keys:
            - bundler-{{ checksum "Gemfile.lock" }}
            - npm-{{ checksum "package-lock.json" }}


      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      
      # Cache Dependencies
      - save_cache:
          paths:
            - vendor/bundle
          key: bundler-{{ checksum "Gemfile.lock" }}

      - run: npm install

        # Cache Dependencies
      - save_cache:
          paths:
            - ~/.cache/npm
          key: npm-{{ checksum "package-lock.json" }}

      # Wait for DB
      # - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the environment
      #- run: cp .sample.env .env

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rake test:system test

      - store_test_results:
          path: test/reports